config/routes.rb
Rails.application.routes.draw do

  get 'topic/index'

  get 'topic/new'

  get 'topic/show'

  devise_for :users

  resources :users, only: [:update]
  
  resources :users do
    resources :weights
  end

  resources :users do
    resources :workouts
  end

  resources :workouts, only: [] do
    resources :exercises
  end

  resources :exercises, only: [] do
    resources :sets, :as => 'ex_sets'
  end

  get 'welcome/about', :as => 'about'

  root to: 'welcome#index', :as => 'welcome'

end

app/models/ex_set.rb
class ExSet < ActiveRecord::Base
  belongs_to :exercise
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :workout
  has_many :ex_sets, dependent: :destroy
  alias_method :sets, :ex_sets
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  #has_many :posts, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :workouts, dependent: :destroy
  has_many :weights, dependent: :destroy
  
  mount_uploader :picture, PictureUploader

end

app/models/weight.rb
class Weight < ActiveRecord::Base
  belongs_to :user
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :user
  has_many :exercises, dependent: :destroy

  def date
    @date = self.created_at
    @date.strftime("%B %d, %Y")
  end
end

app/controllers/sets_controller.rb
class SetsController < ApplicationController

  def new
    @exercise = Exercise.find(params[:exercise_id])
    @set = ExSet.new
  end

  def create
    @exercise = Exercise.find(params[:exercise_id])
    @set = ExSet.new(set_params)
    @set.exercise = @exercise

    if @set.save
      redirect_to [@exercise.workout, @exercise]
    else
      flash[:error] = "Uh oh! We couldn't add your set!"
      redirect_to :new
    end
  end

  def update
    @exercise = Exercise.find(params[:exercise_id])
    @set = ExSet.find(params[:id])
    @set.exercise = @exercise

    if @set.update_attributes(set_params)
      redirect_to :exercise
    else
      flash[:error] = "Uh oh! We couldn't update your set!"
      redirect_to :exercise
    end
  end

  def destroy
    @exercise = Exercise.find(params[:exercise_id])
    @set = ExSet.find(params[:id])
    @set.exercise = @exercise

    if @set.destroy
      redirect_to :exercise
    else
      flash[:error] = "Uh oh! We couldn't delete your set!"
      redirect_to :exercise
    end
  end

  private

  def set_params
    params.require(:set).permit(:order, :reps, :weight)
  end
end

app/controllers/topic_controller.rb
class TopicController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @topic = Topic.all
  end

  def new
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = "User information updated!"
      redirect_to edit_user_registration_path
    else
      flash[:error] = "Error updating user information!"
      redirect_to :back
    end
  end

  def show
    @user = User.find(params[:id])
    @weights = @user.weights
  end

  def index
    @user = User.find(params[:id])
    @weights = @user.weights
  end

  private

  def user_params
    params.require(:user).permit(:name, :picture, :picture_cache)
  end
end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @weights = @user.weights.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.find(params[:user_id])
    @weight = Weight.new
  end

  def create
    @user = User.find(params[:user_id])
    @weight = Weight.new(weight_params)
    @weight.user = @user

    if @weight.save
      flash[:notice] = "Weight recorded!  Keep tracking and check out your progress on the weight history tab."
      redirect_to user_weights_path(@user, @weights)
    else
      flash[:error] = "Weight not recorded!  Try again."
      redirect_to new_user_weight_path
    end
  end

  def show
    @user = User.find(params[:user_id])
    @weight = Weight.find(params[:id])
    @weights = @user.weights.paginate(page: params[:page], per_page: 10)
  end

  def edit
    @user = User.find(params[:user_id])
    @weight = Weight.find(params[:id])
    @weights = @user.weights.paginate(page: params[:page], per_page: 10)
  end

  def update
    @user = User.find(params[:id])
    @weight = Weight.find(params[:id])
    @weights = @user.weights.paginate(page: params[:page], per_page: 10)

    if @weight.update_attributes(weight_params)
      flash[:notice] = "Weight updated!"
      redirect_to user_weight_path
    else
      flash[:error] = "Weight not update!  Try again."
      redirect_to edit_user_weight_path
    end
  end

  private

  def weight_params
    params.require(:weight).permit(:value, :bodyfat)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @workouts = @user.workouts.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.find(params[:user_id])
    @workout = Workout.new
  end

  def create
    @user = User.find(params[:user_id])
    @workout = Workout.new(workout_params)
    @workout.user = @user

    if @workout.save
      flash[:notice] = "Ready?! Go earn those gains!"
      redirect_to user_workout_path(@user, @workout)
    else
      flash[:error] = "Uh oh! Your workout wasn't saved"
      render :new
    end
  end

  def show
    @user = User.find(params[:user_id])
    @workout = Workout.find(params[:id])
    @workouts = @user.workouts.paginate(page: params[:page], per_page: 10)
    @exercises = @workout.exercises
  end

  def edit
    @workout = Workout.find(params[:id])
    @exercises = @workout.exercises
  end

  def update
    @workout = Workout.find(params[:id])

    if @workout.update_attributes(workout_params)
      flash[:notice] = "Workout updated!"
      redirect_to user_workout_path(@user, @workout)
    else
      flash[:error] = "Uh oh, your changes didn't save!"
      redirect_to :back
    end
  end

  def destroy
    @workout = Workout.find(params[:id])

    if @workout.destroy
      flash[:notice] = "Workout deleted!"
      redirect_to workouts_path
    else
      flash[:error] = "Uh oh, your workout wasn't deleted!  Try again!"
      redirect_to :back
    end
  end

  private

  def workout_params
    params.require(:workout).permit(:location, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/sets_helper.rb
module SetsHelper
end

app/helpers/topic_helper.rb
module TopicHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workout_helper.rb
module WorkoutHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gains Track</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <%= javascript_include_tag 'jquery', 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <div class="navbar top-bar">
    <%= link_to welcome_path, class: 'logo' do %>
      <%= image_tag("GainsTrackLogo2.jpg", height:"60", width: "185", alt: "GainsTrackLogo") %>
    <% end %>
      <div class="pull-right user-info">
        <% if current_user %>
          <%= image_tag(current_user.picture.small.url, alt: "Prof. Pic", class: 'profile-pic') if current_user.picture? %>
          <p class="greeting"> Welcome <%= current_user.name || current_user.email %>! </p> &nbsp; &nbsp;
          <%= link_to edit_user_registration_path do %>
            <%= fa_icon "user", class:"fa-2x" %>
          <% end %>
          &nbsp;
          <%= link_to destroy_user_session_path, method: :delete do %>
            <%= fa_icon "sign-out", class:"fa-2x" %>
          <% end %>
        <% else %>
          <%= link_to new_user_session_path, class: "login-links" do %>
            Sign In &nbsp;<%= fa_icon "sign-in", class:"fa-lg" %>
          <% end %>
          <span class="nobr">&nbsp;&nbsp;or&nbsp;&nbsp;</span>
          <%= link_to new_user_registration_path, class: "login-links" do %>
            Sign Up &nbsp;<%= fa_icon "user-plus", class:"fa-lg" %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="nav nav-pills lower-bar">
      <ul class="nav nav-tabs nav-stacked">
        <li class="nav-links"><%= link_to "Home", welcome_path, class: "nav-text" %></li>
        <li class="nav-links"><%= link_to "About", about_path, class: "nav-text" %></li>
        <% if current_user %>
          <li class="nav-links"><%= link_to "Track Weight/BF", new_user_weight_path(current_user.id), class: "nav-text" %></li>
          <li class="nav-links"><%= link_to "Weight History/BF", user_weights_path(current_user.id), class: "nav-text" %></li>
          <li class="nav-links"><%= link_to "New Workout", new_user_workout_path(current_user.id), class: "nav-text" %></li>
          <li class="nav-links"><%= link_to "Workout History", user_workouts_path(current_user.id), class: "nav-text" %></li>
        <% end %>
      </ul>
    </br>
    </br>
    </br>
    </br>
    </div>
    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>
    <div class="container main-page">

      <%= yield %>

    </div>
  </body>
</html>